# yaml-language-server: $schema=https://raw.githubusercontent.com/SchemaStore/schemastore/refs/heads/master/src/schemas/json/dependabot-2.0.json

version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: '06:00'
      timezone: Europe/Stockholm
    reviewers:
      - ackuq
